KS-2-1
soiledz/KotlinSprint pull request #10
Opened 2024-09-17 19:07 UTC by soiledz

понимаю, что этого не было в уроках 
val formattedNumber = String.format("%.2f", average)
 Но я не нашел другого варианта, как выводить по заданному условию

2024-09-18 18:32 UTC, ievetrovdev requested changes
По задаче все хорошо, но на будущее:

2024-09-18 18:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-1.kt
> +    val a: Float = 3.0F
Нужно инициализировать переменные с более осмысленными названиями. человек, который впервые увидит код - не поймет для чего он нужен и что тут происходит

2024-09-18 21:35 UTC, soiledz commented
Изменил название переменных на более осмысленные

2024-09-19 14:58 UTC, ievetrovdev approved these changes
Прекрасно! Аппрув!

Небольшое замечание по поводу неймингов, на будущее, давай дополнительно, после префикса проекта и номера урока писать короткое название, отражающее суть задачи, например:
`KS-2-1-students-average-score`

В будущем это позволит легче ориентироваться в ветках и pr проекта)

2024-09-19 19:12 UTC, merged