KS-2-3
soiledz/KotlinSprint pull request #12
Opened 2024-09-17 21:03 UTC by soiledz

2024-09-18 18:40 UTC, ievetrovdev requested changes

2024-09-18 18:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-3.kt
> +    val travelHours: Int = travelTime / 60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-09-18 21:46 UTC, soiledz commented
Ввел константу.
по поводу Магических чисел, не понял как исправить или избавиться от него

2024-09-19 15:00 UTC, ievetrovdev commented
> Ввел константу. по поводу Магических чисел, не понял как исправить или избавиться от него

Магические числа - голые цифры в коде, не вынесенные в переменную или константу,

2024-09-19 15:01 UTC, ievetrovdev requested changes

2024-09-19 15:01 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-3.kt
> +    val MINUTES_IN_HOUR: Int = 60
Хорошо, но константа инициализируется с помощью слова const

2024-09-19 19:44 UTC, soiledz commented on src/main/kotlin/lesson_2/KS-2-3.kt
> +    val MINUTES_IN_HOUR: Int = 60
не могу понять как использовать слово const, так как выбивает ошибку.

2024-09-20 20:19 UTC, soiledz commented
вынес константу за пределы функции main

2024-09-21 10:49 UTC, ievetrovdev approved these changes

2024-09-21 11:45 UTC, merged