KS-2-4
soiledz/KotlinSprint pull request #13
Opened 2024-09-17 21:15 UTC by soiledz

2024-09-18 18:59 UTC, ievetrovdev requested changes

2024-09-18 18:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-4.kt
> +    val ironBaf = (iron * baf) / 100
“Голые” числа в коде называются [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Не является хорошей практикой. Предлагаю вынести в переменную

2024-09-18 21:50 UTC, soiledz commented
Добавил константу

2024-09-19 15:04 UTC, ievetrovdev requested changes

2024-09-19 15:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-4.kt
> +    val PERCENT: Int = 100
Хорошо, но константа объявляется с помощью слова const

2024-09-19 15:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-4.kt
> +    val kristalBaf = (kristal * baf) / PERCENT
Предлагаю еще вынести расчет коэффициента бафа в отдельную переменную чтобы переиспользовать это значение во всех формулах

2024-09-19 19:42 UTC, soiledz commented on src/main/kotlin/lesson_2/KS-2-4.kt
> +    val kristalBaf = (kristal * baf) / PERCENT
ввел формулу и нашел как преобразовывать в целое число с помощью .toInt()

2024-09-21 10:49 UTC, ievetrovdev approved these changes

2024-09-21 11:45 UTC, merged