KS-2-5 compound interest
soiledz/KotlinSprint pull request #14
Opened 2024-09-19 20:10 UTC by soiledz

Все та же история с использованием const !?

2024-09-20 10:04 UTC, ievetrovdev requested changes

2024-09-20 10:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-5.kt
>      val annualInterestRate = 16.7 / PERCENT
Все же следует только объявить и проинициализировать переменные, а расчеты производить отдельно

2024-09-20 10:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-5.kt
>      val PERCENT = 100
Константы объявляются немного иначе)

2024-09-20 10:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/KS-2-5.kt
>      val annualInterestRate = 16.7 / PERCENT
Также следует вынести 1 в константу, поскольку это [магическое число](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования)

2024-09-21 18:15 UTC, soiledz commented
Вывел константы за пределы функции

2024-09-21 18:19 UTC, ievetrovdev approved these changes

2024-09-21 18:19 UTC, merged