KS-4-4-sport
soiledz/KotlinSprint pull request #23
Opened 2024-09-22 18:35 UTC by soiledz

2024-09-23 19:25 UTC, ievetrovdev requested changes

2024-09-23 19:25 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/KS-4-4.kt
> +    val legsBack = thisDay % 2 == 0
Это по сути одно и тоже, используй только одну переменную, а отрицание перенеси в вывод

2024-09-23 20:25 UTC, merged

2024-09-23 21:12 UTC, ievetrovdev commented
Напоминаю, согласно нашему флоу задачки без аппрува не сливаем. В этот раз принимаю, так как верно исправил, но в будущем так делать нельзя (и тем более на реальном проекте)

2024-09-24 15:11 UTC, soiledz commented
> Напоминаю, согласно нашему флоу задачки без аппрува не сливаем. В этот раз принимаю, так как верно исправил, но в будущем так делать нельзя (и тем более на реальном проекте) 

Это у меня крит ошибку в проекте выбило и я пытался ее пофиксить. Случайно вышло, но спасибо, буду иметь ввиду.