KS-1-task3 variables
soiledz/KotlinSprint pull request #7
Opened 2024-09-16 19:58 UTC by soiledz

2024-09-17 07:33 UTC, ievetrovdev requested changes
По оформлению пулл реквеста:
 - Префикс проекта с названием и номером урока задачи следует прописывать в названии пулл реквеста. Например, "KS-1-1 сделал то-то".

2024-09-17 07:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/Task_3.kt
> +    println("0$hour")
В целом результат есть!
Вообще нормальная практика, если сервер присылает дату или время строкой.
Давай объявим строки и сделаем правильный формат)

2024-09-17 17:43 UTC, soiledz commented on src/main/kotlin/lesson_1/Task_3.kt
> +    println("0$hour")
поискал  как сделать с помощью формат, но не понял как закинуть исправленное в GIT. надеюсь получилось

2024-09-18 06:51 UTC, ievetrovdev approved these changes

2024-09-18 06:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/Task_3.kt
> +    val time = String.format("%4d\n%02d\n%02d", yearFly, hour, minute)
Так тоже можно, но хватило бы сделать данные в виде строки, не просто так я об этом написал
var hour = "09"

2024-09-18 20:02 UTC, merged