KS-1-task5 variables
soiledz/KotlinSprint pull request #9
Opened 2024-09-16 20:40 UTC by soiledz

2024-09-17 07:36 UTC, ievetrovdev requested changes
Так как это 5 задача ("со звездочкой") не по уровню урока, то и решение должно быть более продвинутым (может потребовать дополнительного ресерча). В данном случае нужно получить часы, минуты и секунды программно. То есть высчитать кодом. Если сразу эта задача не дается – можно вернуться к ней позже)

2024-09-17 18:09 UTC, soiledz commented
> Так как это 5 задача ("со звездочкой") не по уровню урока, то и решение должно быть более продвинутым (может потребовать дополнительного ресерча). В данном случае нужно получить часы, минуты и секунды программно. То есть высчитать кодом. Если сразу эта задача не дается – можно вернуться к ней позже)

вроде так, но с пул реквестами после исправления сильно запутался,

2024-09-18 06:58 UTC, ievetrovdev requested changes

2024-09-18 06:58 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/Task_5.kt
> +    val minute = (secondsInSpace - (hour * 3600)) / 60
Да, почти верно.
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это магические числа, что тоже не является хорошей практикой.

2024-09-18 20:58 UTC, soiledz commented
создал константы,

2024-09-19 08:10 UTC, ievetrovdev requested changes

2024-09-19 08:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/Task_5.kt
> +    val SECONDS_IN_MINUTE = 60
Оформление почти верное, но это просто переменный, для констант не хватает ключевого слова const

2024-09-19 19:10 UTC, soiledz commented on src/main/kotlin/lesson_1/Task_5.kt
> +    val SECONDS_IN_MINUTE = 60
Но почему-то ключевое слово const вызывает ошибку Modifier 'const' is not applicable to 'local variable'.

2024-09-20 20:13 UTC, soiledz commented
вывел константы за пределы функции main

2024-09-21 06:52 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/Task_5.kt
> +    val SECONDS_IN_MINUTE = 60
Ответ лежит в самой ошибке, константа должна быть вне исполняемой области

2024-09-21 06:52 UTC, ievetrovdev approved these changes
Отлично!

2024-09-21 09:27 UTC, merged